/**
 * Plan Screen  
 * Shows segment-by-segment race day plan - the thing people screenshot
 */

import React from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  SafeAreaView, 
  ScrollView,
  TouchableOpacity,
  Share,
} from 'react-native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RouteProp } from '@react-navigation/native';
import { HomeStackParamList } from '../navigation/TabNavigator';
import { getRiskColor } from '../lib/api';
import { SegmentPlan } from '../types';

type PlanScreenProps = {
  navigation: NativeStackNavigationProp<HomeStackParamList, 'Plan'>;
  route: RouteProp<HomeStackParamList, 'Plan'>;
};

const SEGMENT_NAMES: Record<string, string> = {
  'RUN': 'Run',
  'SKI_ERG': 'SkiErg',
  'SLED_PUSH': 'Sled Push',
  'SLED_PULL': 'Sled Pull',
  'BURPEE_BROAD_JUMP': 'Burpee BJ',
  'ROW': 'Row',
  'FARMERS_CARRY': 'Farmers',
  'SANDBAG_LUNGES': 'Lunges',
  'WALL_BALLS': 'Wall Balls',
};

export default function PlanScreen({ navigation, route }: PlanScreenProps) {
  const { simulation } = route.params;
  const { segment_plans, predictions } = simulation;

  let runCount = 0;

  const getSegmentDisplayName = (segment: SegmentPlan): string => {
    if (segment.segment_type === 'RUN') {
      runCount++;
      return `Run ${runCount}`;
    }
    runCount = Math.floor(segment.segment_order / 2); // Reset counter for display
    return SEGMENT_NAMES[segment.segment_type] || segment.segment_type;
  };

  const handleShare = async () => {
    try {
      let planText = `🏃 HYROXPace Race Plan\n`;
      planText += `━━━━━━━━━━━━━━━━━━━━━\n`;
      planText += `Target: ${predictions.likely_display}\n\n`;
      
      let rNum = 0;
      segment_plans.forEach((seg) => {
        const name = seg.segment_type === 'RUN' ? `Run ${++rNum}` : SEGMENT_NAMES[seg.segment_type];
        const pace = seg.target_pace_per_km ? ` (${seg.target_pace_per_km})` : '';
        planText += `${name}: ${seg.target_time_display}${pace}\n`;
        planText += `  → ${seg.execution_cue}\n\n`;
      });
      
      planText += `\nGenerated by HYROXPace`;
      
      await Share.share({
        message: planText,
      });
    } catch (error) {
      console.error(error);
    }
  };

  // Reset run counter for render
  runCount = 0;

  return (
    <SafeAreaView style={styles.container}>
      {/* Header with target time */}
      <View style={styles.header}>
        <Text style={styles.headerLabel}>Target Finish</Text>
        <Text style={styles.headerTime}>{predictions.likely_display}</Text>
      </View>

      <ScrollView style={styles.scrollView}>
        {/* Segment Table */}
        <View style={styles.table}>
          {/* Table Header */}
          <View style={styles.tableHeader}>
            <Text style={[styles.headerCell, styles.segmentCol]}>Segment</Text>
            <Text style={[styles.headerCell, styles.timeCol]}>Target</Text>
            <Text style={[styles.headerCell, styles.effortCol]}>Effort</Text>
          </View>

          {/* Table Rows */}
          {segment_plans.map((segment, idx) => {
            const isRun = segment.segment_type === 'RUN';
            const riskColor = getRiskColor(segment.risk_level);
            
            return (
              <View 
                key={segment.segment_order} 
                style={[
                  styles.tableRow,
                  idx % 2 === 0 && styles.tableRowAlt,
                  segment.risk_level === 'high' && styles.tableRowHighRisk,
                ]}
              >
                {/* Segment Name */}
                <View style={styles.segmentCol}>
                  <View style={styles.segmentNameRow}>
                    <View style={[styles.riskDot, { backgroundColor: riskColor }]} />
                    <Text style={[styles.segmentName, isRun && styles.segmentNameRun]}>
                      {getSegmentDisplayName(segment)}
                    </Text>
                  </View>
                  {segment.target_pace_per_km && (
                    <Text style={styles.paceText}>{segment.target_pace_per_km}</Text>
                  )}
                </View>

                {/* Target Time */}
                <View style={styles.timeCol}>
                  <Text style={styles.timeText}>{segment.target_time_display}</Text>
                </View>

                {/* Effort */}
                <View style={styles.effortCol}>
                  <View style={styles.effortBarContainer}>
                    <View 
                      style={[
                        styles.effortBar, 
                        { 
                          width: `${segment.effort_percentage}%`,
                          backgroundColor: segment.effort_percentage > 85 ? '#ef4444' : 
                                          segment.effort_percentage > 75 ? '#f97316' : '#22c55e'
                        }
                      ]} 
                    />
                  </View>
                  <Text style={styles.effortText}>{segment.effort_percentage}%</Text>
                </View>
              </View>
            );
          })}
        </View>

        {/* Execution Cues */}
        <View style={styles.cuesSection}>
          <Text style={styles.sectionTitle}>Execution Cues</Text>
          {segment_plans.map((segment) => {
            const isHighRisk = segment.risk_level === 'high' || segment.risk_level === 'critical';
            let displayRunCount = 0;
            
            return (
              <View 
                key={`cue-${segment.segment_order}`}
                style={[styles.cueCard, isHighRisk && styles.cueCardHighRisk]}
              >
                <View style={styles.cueHeader}>
                  <Text style={styles.cueName}>
                    {segment.segment_type === 'RUN' 
                      ? `Run ${Math.ceil(segment.segment_order / 2)}`
                      : SEGMENT_NAMES[segment.segment_type]}
                  </Text>
                  {isHighRisk && (
                    <View style={styles.riskBadge}>
                      <Text style={styles.riskBadgeText}>⚠️ High Risk</Text>
                    </View>
                  )}
                </View>
                <Text style={styles.cueText}>{segment.execution_cue}</Text>
                {segment.risk_reason && (
                  <Text style={styles.riskReason}>{segment.risk_reason}</Text>
                )}
              </View>
            );
          })}
        </View>

        {/* Legend */}
        <View style={styles.legend}>
          <Text style={styles.legendTitle}>Risk Levels</Text>
          <View style={styles.legendRow}>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#22c55e' }]} />
              <Text style={styles.legendText}>Low</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#eab308' }]} />
              <Text style={styles.legendText}>Moderate</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#f97316' }]} />
              <Text style={styles.legendText}>High</Text>
            </View>
            <View style={styles.legendItem}>
              <View style={[styles.legendDot, { backgroundColor: '#ef4444' }]} />
              <Text style={styles.legendText}>Critical</Text>
            </View>
          </View>
        </View>

      </ScrollView>

      {/* Share Button */}
      <View style={styles.footer}>
        <TouchableOpacity style={styles.shareButton} onPress={handleShare}>
          <Text style={styles.shareButtonText}>📤 Share Race Plan</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
  },
  header: {
    backgroundColor: '#1f2937',
    padding: 16,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  headerLabel: {
    color: '#9ca3af',
    fontSize: 12,
  },
  headerTime: {
    color: '#f97316',
    fontSize: 32,
    fontWeight: '700',
    letterSpacing: 2,
  },
  scrollView: {
    flex: 1,
  },
  table: {
    margin: 12,
    backgroundColor: '#1f2937',
    borderRadius: 12,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#374151',
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  headerCell: {
    color: '#9ca3af',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  segmentCol: {
    flex: 2,
  },
  timeCol: {
    flex: 1,
    alignItems: 'center',
  },
  effortCol: {
    flex: 1.2,
    alignItems: 'flex-end',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#374151',
  },
  tableRowAlt: {
    backgroundColor: 'rgba(55, 65, 81, 0.3)',
  },
  tableRowHighRisk: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  segmentNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  riskDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  segmentName: {
    color: '#e5e7eb',
    fontSize: 14,
    fontWeight: '500',
  },
  segmentNameRun: {
    color: '#60a5fa',
  },
  paceText: {
    color: '#6b7280',
    fontSize: 11,
    marginLeft: 16,
    marginTop: 2,
  },
  timeText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  effortBarContainer: {
    width: 50,
    height: 6,
    backgroundColor: '#374151',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 4,
  },
  effortBar: {
    height: '100%',
    borderRadius: 3,
  },
  effortText: {
    color: '#9ca3af',
    fontSize: 11,
  },
  cuesSection: {
    padding: 12,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  cueCard: {
    backgroundColor: '#1f2937',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  cueCardHighRisk: {
    borderLeftWidth: 3,
    borderLeftColor: '#f97316',
  },
  cueHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  cueName: {
    color: '#e5e7eb',
    fontSize: 14,
    fontWeight: '600',
  },
  riskBadge: {
    backgroundColor: '#7f1d1d',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 4,
  },
  riskBadgeText: {
    color: '#fca5a5',
    fontSize: 11,
  },
  cueText: {
    color: '#9ca3af',
    fontSize: 13,
    lineHeight: 18,
  },
  riskReason: {
    color: '#f97316',
    fontSize: 12,
    marginTop: 6,
    fontStyle: 'italic',
  },
  legend: {
    padding: 12,
    marginBottom: 20,
  },
  legendTitle: {
    color: '#6b7280',
    fontSize: 12,
    marginBottom: 8,
  },
  legendRow: {
    flexDirection: 'row',
    gap: 16,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  legendText: {
    color: '#9ca3af',
    fontSize: 12,
  },
  footer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#374151',
  },
  shareButton: {
    backgroundColor: '#f97316',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  shareButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
});